### ISSUE TITLE
Cant edit config via mod menu

### ISSUE THREAD

**Issue by Sero-Tepes** [fzzyhmstrs/pc#22] opened 2024-09-10 12:16 UTC
When i try to edit the config in game it says "cant edit"
![huge_2024-09-10_14 13 33](https://github.com/user-attachments/assets/136e19db-ff49-42cd-a3bf-3b23bfe236ea)

**Comment by fzzyhmstrs** [comment] 2024-09-10 20:55
with PC 0.2.2 and Fzzy Config 0.4.1 I can't replicate this issue. Both using Mod Menu and using the /configure command
![image](https://github.com/user-attachments/assets/618b32ed-e843-41c2-8b35-04a1f950521d)

**Comment by Franco227** [comment] 2024-09-11 23:39
This is caused by Sodium Extra, which adds more precise settings for particle control

**Comment by fzzyhmstrs** [comment] 2024-09-12 02:46
That doesn't appear to be true? The last SE update was 7 months ago, before Particle Core even released. Maybe on newer versions of the game, but I can't quickly find any evidence of that.
![image](https://github.com/user-attachments/assets/307c7905-20a9-47ee-b4a1-ff576ca595d5)

**Comment by Franco227** [comment] 2024-09-12 22:52
Tried with the following mods on Minecraft 1.21 and was able to reproduce

Mod Menu 11.0.2
Sodium 0.6.0-beta.1
Sodium Extra 0.6.0-beta.1
ParticleCore 0.2.4+1.21
FzzyConfig 0.4.1+1.21

(also latest Sodium Extra update is from 2 weeks ago)

**Comment by fzzyhmstrs** [comment] 2024-09-12 23:56
The update from the picture is from 1.20.1, so not the latest Sodium Extras update.

**Comment by fzzyhmstrs** [comment] 2024-09-13 00:25
Ok I was able to replicate this, and work around it. It has nothing to do with Sodium Extras. It has to do with the fact that Mod Menu caches the screen (apparently), and that Fzzy Config isn't properly letting you edit client-only settings outside of a game. If you use `/configure particle_core` it opens just fine. The indev version of Fzzy Config should improve the permission checking of client-only configs, I'll close this when that hits release.
![image](https://github.com/user-attachments/assets/d128da32-2c51-4354-b86b-1db076047206)

**Comment by fzzyhmstrs** [comment] 2024-09-21 15:37
0.4.3 has the imporved permission checking as mentioned above

**Closed by fzzyhmstrs** 2024-09-21 15:37 UTC
